# Generated by Django 5.2.1 on 2025-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('moderator', 'Moderator'), ('speaker', 'Speaker')], max_length=10)),
                ('description_kz', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
            ],
        ),
    ]
