# Generated by Django 5.2.1 on 2025-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_speaker_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_kz', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('url_kz', models.URLField()),
                ('url_ru', models.URLField()),
                ('url_en', models.URLField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='news/')),
            ],
        ),
    ]
