# Generated by Django 5.2.1 on 2025-05-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_speaker_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
