# Generated by Django 5.2.1 on 2025-05-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('session', models.CharField(choices=[('aiIntegration', 'Integration of Artificial Intelligence in Public Service'), ('fishbowlSession', 'Fishbowl Session - Development of Unified Personnel Management Systems'), ('foresightSession', 'Foresight Session - Proactive, Data-Driven HR Strategies and Strategic Workforce Planning'), ('trainingDevelopment', 'Training and Competency Development for Civil Servants')], max_length=20)),
                ('consent', models.BooleanField(default=False)),
                ('foresight_topics', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
