# Generated by Django 5.2.1 on 2025-05-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_registration_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
