# Generated by Django 5.2.1 on 2025-05-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_registration_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='iin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
