# Generated by Django 5.2.1 on 2025-07-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_registration_iin'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
